# Generated by Django 3.0.8 on 2020-07-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('birth_year', models.CharField(max_length=10)),
                ('eye_color', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Undisclosed', 'Undisclosed')], default='Undisclosed', max_length=15)),
                ('height', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('edited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_height', models.FloatField()),
                ('average_lifespan', models.PositiveIntegerField()),
                ('classification', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=20)),
                ('eye_colors', models.CharField(max_length=100)),
                ('hair_colors', models.CharField(max_length=100)),
                ('skin_colors', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=15)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
